### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser 

### ISSUE THREAD

**Issue by ashkryab** [iamthevoid/media-picker-android#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:605)
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
        at iam.thevoid.mediapicker.builder.PhotoIntentBuilder.build(PhotoIntentBuilder.java:48)
        at iam.thevoid.mediapicker.rxmediapicker.Purpose$Take$1.getIntent(Purpose.java:38)
        at iam.thevoid.mediapicker.rxmediapicker.RxMediaPicker.onlyOneAppCanHandleRequest(RxMediaPicker.java:170)
        at iam.thevoid.mediapicker.rxmediapicker.RxMediaPicker.startSelection(RxMediaPicker.java:96)
        at iam.thevoid.mediapicker.rxmediapicker.RxMediaPicker.lambda$DGXq789l8MUhPIq0MQqtfjat-Jc(Unknown Source:0)
        at iam.thevoid.mediapicker.rxmediapicker.-$$Lambda$RxMediaPicker$DGXq789l8MUhPIq0MQqtfjat-Jc.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:898)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6716)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ashkryab** [comment]
add provider to manifest
